### ISSUE TITLE
`append` to non-existent stream "hangs"

### ISSUE THREAD

**Issue by shikhar** [s2-streamstore/streamstore-cli#61]
It only prints the error about stream not existing when you try to Ctrl+C out (even after trying to flush some messages).

**Comment by infiniteregrets** [comment]
this wasnt the case earlier when testing with non existent streams or basins, the issue is probably upstream in the sdk

**Comment by vrongmeal** [comment]
> this wasnt the case earlier when testing with non existent streams or basins, the issue is probably upstream in the sdk

doesn't seem like it. added some logs to see, what's basically happening is the error being returned in the next iteration somehow from CLI, which is very weird

**Comment by vrongmeal** [comment]
Having a `break` instead of `return` here somehow resolves the issue :/
